data:
  host: localhost
  port: 3306
  user: root
  database: root
  password: root
messages:
  opening: '&c!!! &fКейс в данный момент открывается'
  badkey: '&c!!! &fКлюч не от этого кейса!'
  notkey: '&c!!! &fЭто кейс. Ключ вы можете приобрести в /donate'
limit: 8